# Application
spring.application.name=spring-gym-app

# Import additional property files
spring.config.import=classpath:hibernate.properties,classpath:flyway.properties,classpath:jwt.properties

# Server
server.port=8080

# HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=GymAppHikariPool
spring.datasource.hikari.auto-commit=false

# Logging
logging.level.dev.ilkersahin=INFO

# Actuator defaults (can be overridden per profile)
management.metrics.tags.application=${spring.application.name}
management.metrics.enable.jvm=true
management.metrics.enable.hikaricp=true

# Enable HTTP request metrics
management.metrics.web.server.request.autotime.enabled=true
management.metrics.web.server.request.autotime.percentiles=0.5,0.95,0.99
management.metrics.web.server.request.autotime.histogram=true
