# Database
spring.datasource.url=jdbc:mysql://stg-db:3306/gymapp
spring.datasource.username=gymapp_stg
spring.datasource.password=${GYMAPP_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Logging
spring.jpa.show-sql=false

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
