# Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.fetch_size=50

spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
