{
 "title": "Spring Gym – Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "gym_users" }
   ]
  },
  {
   "title": "Total Trainees",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "gym_trainees" }
   ]
  },
  {
   "title": "Total Trainers",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "gym_trainers" }
   ]
  },
  {
   "title": "Total Training Minutes",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "gym_training_duration_total_minutes"
    }
   ]
  },
  {
   "title": "HTTP Requests (All)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 16, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  }
 ]
}