spring.application.name=spring-gym-workload
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://gymapp_user:gymapp_password@localhost:27017/workloaddb?authSource=admin
spring.data.mongodb.auto-index-creation=true

# JWT (shared secret with main app)
jwt.secret=de83f7444a231cefb372ce157e70246dafbdea73332cbbed349b570c31f68ddd

# ActiveMQ Artemis
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=artemis

# Logging
logging.level.dev.ilkersahin=INFO
