spring.application.name=spring-gym-workload
server.port=8082

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:workloaddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (shared secret with main app)
jwt.secret=de83f7444a231cefb372ce157e70246dafbdea73332cbbed349b570c31f68ddd

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.level.dev.ilkersahin=INFO
